DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR (50),
password VARCHAR (256),
role VARCHAR (10)
);

DROP TABLE IF EXISTS team;

CREATE TABLE TEAM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    league VARCHAR(50),
    country VARCHAR(50)
);